on:
  push:
    branches:
      - staging
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cyriandev.co.za
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/organizer/ #change this to /public_html/organizer-staging/(staging subdomain folder name)


          # this file is for the staging branch, what i am trying to figure out is how this works, does it run in the defined linux environment or does it run on the server?
